// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// heat_model
DataFrame heat_model(List input_vct, List input_ind, float hloss, float sheat, bool expand);
RcppExport SEXP _eflows_heat_heat_model(SEXP input_vctSEXP, SEXP input_indSEXP, SEXP hlossSEXP, SEXP sheatSEXP, SEXP expandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type input_vct(input_vctSEXP);
    Rcpp::traits::input_parameter< List >::type input_ind(input_indSEXP);
    Rcpp::traits::input_parameter< float >::type hloss(hlossSEXP);
    Rcpp::traits::input_parameter< float >::type sheat(sheatSEXP);
    Rcpp::traits::input_parameter< bool >::type expand(expandSEXP);
    rcpp_result_gen = Rcpp::wrap(heat_model(input_vct, input_ind, hloss, sheat, expand));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eflows_heat_heat_model", (DL_FUNC) &_eflows_heat_heat_model, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_eflows_heat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
