# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate predictions of inside temperature
#'
#' @param input_vct List or DF of vectorized input parameters.
#' @param input_ind List or DF of parameters with length one.
#' @param hloss heat loss of the building.
#' @param sheat specific heat of the building.
#' @param expand more detailed resuts.
#' @export
heat_model <- function(input_vct, input_ind, hloss, sheat, expand = FALSE) {
    .Call('_eflows_heat_heat_model', PACKAGE = 'eflows.heat', input_vct, input_ind, hloss, sheat, expand)
}

